# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Domen R.
tagline:          'Personal website'
description:      'Computer Vision & Deep Learning Engineer.'
#url:              /
baseurl:          /

author:
  name:           'Domen R.'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
linkedin:
  url:           https://www.linkedin.com/in/domenracki
github:
  url:           https://github.com/donrax
