# Dependencies
#markdown:         kramdown
markdown:         maruku
highlighter:      rouge

# Setup
title:            Domen Racki
tagline:          'blog'
description:      'Computer Vision & Deep Learning Engineer.'
#url:              /
baseurl:          /

author:
  name:           'Domen R.'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
linkedin:
  url:           https://www.linkedin.com/in/domenracki
github:
  url:           https://github.com/donrax
