# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Domen R.
tagline:          'Personal website'
description:      'Computer Vision & Deep Learning Engineer.'
#url:              http://hyde.getpoole.com
baseurl:          / #https://donrax.github.io

author:
  name:           'Domen R.'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
#version:          2.1.0

linkedin:
  url:           https://www.linkedin.com/in/domenracki
github:
  url:           https://github.com/donrax
