# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Domen R.
tagline:          'Personal website'
description:      'Computer Vision & Deep Learning Engineer.'
#url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Domen R.'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
